seaweedfs/seaweedfs-operator

controllers/controller_filer_statefulset.go, controllers/controller_volume_statefulset.go, controllers/helper.go
Fuse mounts with direct connections to volume servers will not work when app and seaweedfs deployments are in different namespaces. Seaweedfs should report volume server addresses with namespace.
=> Always use dns names with namespace

controllers/controller_master.go
Reconciler would get stuck since ensuring the number of desired masters never succeeds since StatefulSets replicas are never updated.
=> update master StatefulSets replicas

README.md
PR following issue #62 
Just add more info in README about manager image to be built and pushed before using operator.
=> Add details in README about manager image build/publish before deployment

config/crd/patches/cainjection_in_seaweeds.yaml, config/crd/patches/webhook_in_seaweeds.yaml, config/default/webhookcainjection_patch.yaml, config/rbac/auth_proxy_client_clusterrole.yaml, config/webhook/manifests.yaml
I've updated the following deprecated apiVersions:
* apiextensions.k8s.io/v1beta1 (CustomResourceDefinition)
* admissionregistration.k8s.io/v1beta1 (MutatingWebhookConfiguration/ValidatingWebhookConfiguration)
* rbac.authorization.k8s.io/v1beta1 (ClusterRole)
The changes regarding the Webhooks are untested as I don't use this feature.
Fixes #61 and maybe also #52.
=> Update deprecated API versions of Kubernetes resources

config/rbac/leader_election_role.yaml
This adds permissions for leases to the leader election role, so that Pods are created again. I've also tested that this change works. Pods are created as usual again.
Fixes #65
PS: Could you please add the `hacktoberfest` topic to the repository or `hacktoberfest-accepted` labels to my two PRs, so that they count towards my contributions for hacktoberfest? :+1:
=> Add permission for leases to leader election role

controllers/controller_filer_ingress.go, controllers/controller_util.go
Updates the Ingress API to networking v1; the beta API is not supported anymore since 1.22.
Note: the build failure has been in the build pipeline before, local builds seem to go through.
=> Update deprecated Ingress API

.github/workflows/image.yml, config/manager/kustomization.yaml
This PR adds a public docker image to this repository. That simplifies the deployment of the seaweedfs-operator in Kubernetes clusters and removes the need to run anything but kustomize. This change should be fully compatible with the existing workflows as the image is overridden in Makefile's `deploy` job. Therefore people that modify the image will still be use to update their operator with the same commands and new users can just deploy it with the official docker image.
The image will be deployed to the free github container registry of this repository.
If this PR gets merged, I'd be happy if you could add the `hacktoberfest-accepted` label again! :+1:
=> Publish official docker image

README.md, deploy/helm/.helmignore, deploy/helm/Chart.yaml, deploy/helm/crds/seaweed.seaweedfs.com_seaweeds.yaml, deploy/helm/dashboard/seaweedfs-grafana-dashboard.json, deploy/helm/templates/_helpers.tpl, deploy/helm/templates/configmap-grafana-dashboard.yaml, deploy/helm/templates/container-registry-secret.yaml, deploy/helm/templates/deployment.yaml, deploy/helm/templates/rbac/leader_election_role.yaml, deploy/helm/templates/rbac/leader_election_role_binding.yaml, deploy/helm/templates/rbac/role.yaml, deploy/helm/templates/rbac/role_binding.yaml, deploy/helm/templates/rbac/seaweed_editor_role.yaml, deploy/helm/templates/rbac/seaweed_viewer_role.yaml, deploy/helm/templates/service.yaml, deploy/helm/templates/servicemonitor.yaml, deploy/helm/templates/webhook/mutating-webhook.yaml, deploy/helm/templates/webhook/service.yaml, deploy/helm/templates/webhook/validating-webhook.yaml, deploy/helm/values.yaml
Now only Kustomize can be used to deploy an operator. Although it is a good tool, Helm is more popular. In my case, I'm using a GitOps approach using Flux2 and CRD HelmRelease. 
This Helm Chart supports the following:
- Deploy seaweedfs-operator
- Deploy SeaweedFS CRD
- ServiceMonitor
- Webhooks
- Pull image from private registry
- Grafana Dashboard deploy
- Override resources requests and limits for operator deployment
- RBAC
=> Add helm chart for deploy SeaweedFS operator

deploy/helm/templates/deployment.yaml
bug: when set webhook.enabled=false in helm ，it cannot work well。
this is pr resolve it.
=> fix webhook.enabled in helm

controllers/controller_filer_statefulset.go, controllers/controller_master_statefulset.go, controllers/controller_volume_statefulset.go
Currently annotations can be specified in the CRD, but are never passed through to the templates of the StatefulSets. This PR adds functionality for those annotations in the seaweed CRD.
=> Pass annotations for the StatefulSets through

Dockerfile
The numeric ID of `nonroot` user and group should be used, so that `spec.template.spec.containers.securityContext.runAsNonRoot` of the Kubernetes deployment can be set and verified. This check only supports numeric users at the moment.
Here can be seen, that the user and group ID of `nonroot` is `65532`: https://github.com/GoogleContainerTools/distroless/blob/main/base/base.bzl#L8
And here is the problem: https://stackoverflow.com/a/49729786
=> Use numeric user id for nonroot verification

deploy/helm/templates/rbac/leader_election_role.yaml
Fixes error: `E0517 17:50:21.216754       1 leaderelection.go:330] error retrieving resource lock seaweedfs/674006ec.seaweedfs.com: leases.coordination.k8s.io "674006ec.seaweedfs.com" is forbidden: User "system:serviceaccount:seaweedfs:default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "seaweedfs"`
Same as https://github.com/seaweedfs/seaweedfs-operator/pull/68 but for helm template
=> helm: add permission for leases to leader election role

.github/workflows/helm_chart_release.yml
This new file, `helm_chart_release.yml`, uses [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action) to create helm chart releases on any push to the `master` branch that changes a file in the `deploy/helm` directory. This also adds automatic release notes generation which will link to the PR that was merged.
Fixes #79 (Publish Helm Charts).
You can see an example of this in action in the nextcloud helm chart repo:
https://github.com/nextcloud/helm/blob/main/.github/workflows/release.yaml
This is what our releases look like for the nextcloud helm chart:
https://github.com/nextcloud/helm/releases
Let me know if there's anything you'd like me to amend :+1:
=> Create helm_chart_release.yml to add helm chart release GitHub Actions Workflow

deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/values.yaml
This PR adds some more comments to the values.yaml, bumps the chart version a patch, and sets defaults so that typing can be determined easier. I also generated a README.md in the helm chart directory to help guide users a bit easier.
I used [norwoodj/helm-docs](https://github.com/norwoodj/helm-docs) to generate the docs, which is why you see this for example:
```yaml
parameter: "some value"
```
The `# --` signifies that the comment should be part of the autogenerated documentation. I've also set defaults for several parameters, keeping in mind that they should be empty if they're not in use by default, as this helps the auto-generated docs determine the defaults/type of the parameter.
You can see an example of what the docs look like here on my feature branch: …
=> Add more comments to the values.yaml, including type hints, and generate a README.md based on those values.

controllers/controller_filer_statefulset.go
Fixes https://github.com/seaweedfs/seaweedfs-operator/issues/101
successfully tested with generated image `greenmaid/seaweedfs-operator:33793af`
=> Fix controler crash by checking if persistence is not nil

Makefile, api/v1/seaweed_webhook.go, config/crd/bases/seaweed.seaweedfs.com_seaweeds.yaml, config/manager/kustomization.yaml, config/rbac/role.yaml, config/webhook/manifests.yaml, go.mod
Hi @chrislusf,
I hope this message finds you well.
I'm new to SeaweedFS and have been thoroughly impressed with your work on the project. I have experience in operator development, particularly with the [etcd-operator](https://github.com/aenix-io/etcd-operator), and I currently have some free time.
I'd love to contribute to the development of SeaweedFS's operator. To get started, I've prepared an initial commit that makes the manifests renderable.
Looking forward to collaborating with you!
Best regards,
@hiddenmarten
=> [81] Manifests rendering fix

cmd/main.go, deploy/helm/templates/rbac/role.yaml, internal/controller/controller_util.go
When the Metrics port is specified for the master or volume's spec in values.yaml,  the operator tries to deploy an object "ServiceMonitor" in order to notify Prometheus of the deployed probe. 
However, ServiceMonitor is a custom object that requires to be included in the operator's schema before being used (for creation or update). Currently, the operator fails when managing the object, and cannot go further:
`"error": "no kind \"ServiceMonitor\" is registered for version \"monitoring.coreos.com/v1\" in scheme \"pkg/runtime/scheme.go:100\""`
We need to include the monitorv1 API Spec in the Reconciler schema at the init phase before trying to manage ServiceMonitors via Kube API
Moreover, some RBAC rules need to be included in the Chart to leverage sufficient privileges.
=> Fix: "no kind ServiceMonitor is registered for version monitoring.coreos.com/v1"

.github/workflows/helm_chart_release.yml
publish chart when new tag is created and use stefanprodan/helm-gh-pages@master for publishing helm charts
=> Try fixing Helm Chart Release

Makefile
This PR updates the `docker-build` and `docker-push` commands within the Makefile to respect the `CONTAINER_TOOL` variable already used elsewhere.
=> Podman for build and push steps

Makefile, README.md
This PR makes it easier to build and deploy the SeaweedFS Operator across different architectures (like amd64 and arm64). Changes include:
- Added `TARGETARCH` and `TARGETOS` support in the Makefile
- Docker builds now pass `--platform` and `--build-arg` correctly
- Marked Makefile targets as `.PHONY` to avoid weird issues
- Updated the README:
- Explained new build options with examples
Should make local dev + CI/CD workflows smoother, especially on arm machines.
I'm not sure about the contribution guidelines for this repo, so if you have any feedback or preferred conventions, feel free to let me know and I’ll be happy to adjust this PR accordingly.
=> Support for multi-architecture docker builds using environment variables

.github/workflows/image.yml
I've tried to deploy the operator in an arm64 k3s cluster but found out that this is not supported. I hope this fixes the latest build failure and allow us to test seaweedfs :grimacing:
=> Setup qemu for cross-platform builds of the operator container image

.github/workflows/image.yml
As we can see in: https://console.cloud.google.com/artifacts/docker/distroless/us/gcr.io/static/sha256:627d6c5a23ad24e6bdff827f16c7b60e0289029b0c79e9f7ccd54ae3279fb45f;tab=manifest?inv=1&invt=Ab2lFw 
linux/386 is not supported by gcr.io/distroless/static:nonroot image.
=> Removed linux/386 to preserve compatibility with gcr.io/distroless/static:nonroot image
